name: fasthistory
adopt-info: testfh
summary: testfh-summary
base: core20
confinement: classic # NOTE: strict is not possible because of the past-into-terminal core feature and copy-to-clipboard limitation  
#confinement: devmode # test mode
#grade: devel

parts:
  testfh:
    plugin: python
    source: .
    # https://snapcraft.io/docs/using-external-metadata#heading--setup-py
    parse-info: [setup.py]

#plugs:
#  test-hook3:
#    interface: personal-files
#    read:
#    - $HOME/.bashrc
#    - $HOME/.zshrc
#    write:
#    - $HOME/.bashrc
#    - $HOME/.zshrc

apps:
  testfh:
    # https://forum.snapcraft.io/t/failed-to-generate-snap-metadata-errors/8955
    command: bin/ftest
    #command: bin/ftestdebug
    #plugs:
    #  - test-hook3